/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as GatewayRouteImport } from './routes/gateway'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewayRoute = GatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gateway': typeof GatewayRoute
  '/usuarios': typeof UsuariosRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gateway': typeof GatewayRoute
  '/usuarios': typeof UsuariosRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes': typeof ClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gateway': typeof GatewayRoute
  '/usuarios': typeof UsuariosRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gateway' | '/usuarios' | '/clientes/$id' | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gateway' | '/usuarios' | '/clientes/$id' | '/clientes'
  id:
    | '__root__'
    | '/'
    | '/gateway'
    | '/usuarios'
    | '/clientes/$id'
    | '/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GatewayRoute: typeof GatewayRoute
  UsuariosRoute: typeof UsuariosRoute
  ClientesIdRoute: typeof ClientesIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateway': {
      id: '/gateway'
      path: '/gateway'
      fullPath: '/gateway'
      preLoaderRoute: typeof GatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GatewayRoute: GatewayRoute,
  UsuariosRoute: UsuariosRoute,
  ClientesIdRoute: ClientesIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
